import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import styles from "@/styles/page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <div className={styles.center}>{children}</div>
      </body>
    </html>
  );
}
