name: Frontend Dev Server CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: 배포 수행
        run: |
          git pull origin ${{ github.head_ref }}
          npm install
          npm run build
          sudo pm2 delete freebe3000
          sudo pm2 start ecosystem_3000.config.js
