name: Frontend Dev Server CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 배포 수행
        run: |
          git pull
          npm install
          npm run buid
          sudo pm2 delete freebe3000
          sudo pm2 start ecosystem_3000.config.js
