name: Frontend Dev Server CI

on:
  pull_request:
    branches: 
      - develop
      - dev-infra-test

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: npm install --force

      - name: Set environment variables # 환경변수 설정
        run: echo "NEXT_PUBLIC_API_DOMAIN="https://api.freebe.co.kr/"" >> $GITHUB_ENV

      - name: Set environment variables
        run: echo "NEXT_PUBLIC_DOMAIN="https://www.freebe.co.kr"" >> $GITHUB_ENV

      - name: Build # React Build
        run: npm run build
